ingress-nginx:
  controller:
    hostPort:
      enabled: true
      ports:
        http: 80
        https: 443
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
    kind: DaemonSet
    service:
      type: ""
